#include "nova64/cpu/cpu.hpp"
#include "nova64/bus/bus.hpp"
#include <stdexcept>
#include <string>
#include <climits>
namespace nova64 {
uint64_t Cpu::physical(uint64_t v,AccessType t){return mmu_.translate(v,t,uint32_t(cp0_.read(10)));}
void Cpu::reset(uint64_t p){s_={};s_.pc=p;s_.next_pc=p+4;delay_slot_=false;cp0_=Cp0{};}
void Cpu::exception(ExceptionCode c,uint64_t bad,bool ds){cp0_.raise(c,bad,current_pc_,ds);s_.pc=0xFFFFFFFF80000180ull;s_.next_pc=s_.pc+4;delay_slot_=false;}
void Cpu::step(){if(s_.halted)return;bool ds=delay_slot_;uint64_t pc=s_.pc,next=s_.next_pc; current_pc_=pc;uint32_t ins=0;try{ins=uint32_t(bus_->read(physical(pc,AccessType::Execute),AccessSize::U32));}catch(const std::exception&e){auto m=std::string(e.what());exception(m.find("TLB")!=std::string::npos?ExceptionCode::TlbLoad:ExceptionCode::BusInstruction,pc,ds);return;}s_.pc=next;s_.next_pc=next+4;delay_slot_=false;uint32_t op=ins>>26,rs=(ins>>21)&31,rt=(ins>>16)&31,rd=(ins>>11)&31,sh=(ins>>6)&31,fn=ins&63;int16_t imm=static_cast<int16_t>(ins);uint64_t a=reg(rs),b=reg(rt);auto mem=[&](uint64_t addr,AccessSize z, bool wr,uint64_t val=0)->uint64_t{if((addr&(uint64_t(z)-1))!=0){exception(wr?ExceptionCode::AddressStore:ExceptionCode::AddressLoad,addr,ds);return 0;}try{auto p=physical(addr,wr?AccessType::Write:AccessType::Read);if(wr){bus_->write(p,val,z);return 0;}return bus_->read(p,z);}catch(const std::exception&e){auto m=std::string(e.what());exception(m.find("modified")!=std::string::npos?ExceptionCode::TlbMod:m.find("TLB")!=std::string::npos?(wr?ExceptionCode::TlbStore:ExceptionCode::TlbLoad):(wr?ExceptionCode::AddressStore:ExceptionCode::AddressLoad),addr,ds);return 0;}};
switch(op){case 0:switch(fn){case 0x20:if((int64_t)(int32_t)a+(int64_t)(int32_t)b>INT32_MAX||(int64_t)(int32_t)a+(int64_t)(int32_t)b<INT32_MIN){exception(ExceptionCode::Overflow,pc,ds);return;}set_reg(rd,uint64_t(int64_t(int32_t(a)+int32_t(b))));break;case 0x21:set_reg(rd,a+b);break;case 0x22:if((int64_t)(int32_t)a-(int64_t)(int32_t)b>INT32_MAX||(int64_t)(int32_t)a-(int64_t)(int32_t)b<INT32_MIN){exception(ExceptionCode::Overflow,pc,ds);return;}set_reg(rd,uint64_t(int64_t(int32_t(a)-int32_t(b))));break;case 0x24:set_reg(rd,a&b);break;case 0x25:set_reg(rd,a|b);break;case 0x26:set_reg(rd,a^b);break;case 0x27:set_reg(rd,~(a|b));break;case 0:set_reg(rd,b<<sh);break;case 2:set_reg(rd,b>>sh);break;case 8:s_.next_pc=a;delay_slot_=true;break;case 9:set_reg(rd,pc+8);s_.next_pc=a;delay_slot_=true;break;case 0x10:set_reg(rd,s_.hi);break;case 0x12:set_reg(rd,s_.lo);break;case 0x18:{int64_t p=int64_t(int32_t(a))*int64_t(int32_t(b));s_.lo=uint64_t(p);s_.hi=uint64_t(p)>>32;break;}case 0x19:s_.lo=a*b;break;case 0x1a:if(b){s_.lo=uint64_t(int32_t(a)/int32_t(b));s_.hi=uint64_t(int32_t(a)%int32_t(b));}break;case 0x0c:exception(ExceptionCode::Syscall,pc,ds);return;case 0x0d:exception(ExceptionCode::Break,pc,ds);return;default:exception(ExceptionCode::Reserved,pc,ds);return;}break;case 1:break;case 2:s_.next_pc=(pc&0xFFFFFFFFF0000000ull)|(uint64_t(ins&0x03ffffff)<<2);delay_slot_=true;break;case 3:set_reg(31,pc+8);s_.next_pc=(pc&0xFFFFFFFFF0000000ull)|(uint64_t(ins&0x03ffffff)<<2);delay_slot_=true;break;case 4:if(a==b){s_.next_pc=next+(int32_t(imm)<<2);delay_slot_=true;}break;case 5:if(a!=b){s_.next_pc=next+(int32_t(imm)<<2);delay_slot_=true;}break;case 8:{int64_t x=int64_t(int32_t(a))+imm;if(x>INT32_MAX||x<INT32_MIN){exception(ExceptionCode::Overflow,pc,ds);return;}set_reg(rt,uint64_t(x));break;}case 9:set_reg(rt,a+int64_t(imm));break;case 0xc:set_reg(rt,a&(ins&65535));break;case 0xd:set_reg(rt,a|(ins&65535));break;case 0xf:set_reg(rt,uint64_t(ins&65535)<<16);break;case 0x10:{uint32_t sub=(ins>>21)&31;if(sub==0)set_reg(rt,cp0_.read(rd));else if(sub==4)cp0_.write(rd,a);else if(sub==16&&fn==0x18){cp0_.eret();s_.pc=cp0_.epc();s_.next_pc=s_.pc+4;}else if(sub==16&&(fn==0x01||fn==0x02||fn==0x06||fn==0x08)){if(fn==1){int i=mmu_.tlb().probe(cp0_.entryhi());cp0_.set_index(i<0?0x80000000u:i);}else if(fn==2){auto e=mmu_.tlb().read(cp0_.index());cp0_.set_entryhi(e.entry_hi);cp0_.set_entrylo0(e.lo0);cp0_.set_entrylo1(e.lo1);cp0_.set_page_mask(e.page_mask);}else {TlbEntry e{cp0_.page_mask(),cp0_.entryhi(),cp0_.entrylo0(),cp0_.entrylo1()};unsigned i=fn==6?cp0_.index()&31:mmu_.tlb().random(cp0_.read(6));mmu_.tlb().write(i,e);}}break;}case 0x23:set_reg(rt,mem(a+int64_t(imm),AccessSize::U32,false));break;case 0x2b:mem(a+int64_t(imm),AccessSize::U32,true,b);break;case 0x37:set_reg(rt,mem(a+int64_t(imm),AccessSize::U64,false));break;case 0x3f:mem(a+int64_t(imm),AccessSize::U64,true,b);break;default:exception(ExceptionCode::Reserved,pc,ds);return;}s_.gpr[0]=0;cp0_.tick();}
void Cpu::run(uint64_t n){while(n--&&!s_.halted)step();}
}
